baseURL: https://caseylees.ca

languageCode: en-us
title: Casey Lees
theme: toha

# Manage languages
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable global emoji support
enableEmoji: true

params:
  # Background image of the landing page
  background: /images/site/background.png

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  logo:
    # main: /images/site/main-logo.png
    # inverted: /images/site/inverted-logo.png
    favicon: /images/site/favicon.jpg

  features:
    portfolio:
      enable: true
    blog:
      enable: false
    notes:
      enable: false

  footer:
    navigation:
      enable: true
    contactMe:
      enable: true
    newsletter:
      enable: false
    credentials:
      enable: true
    disclaimer:
      enable: false